# Data preprocessing: Date extraction

**NOTEBOOK GOAL**: Extract attributes: Day, Month and Year from the Date attribute

**DATASET TRANSFORMATION**: `train.csv` >> `preprocessed0_date_train.csv`

In [1]:
from import_man import *

from datetime import datetime

In [2]:
df = pd.read_csv('./dataset/train.csv')
df.head()

,StoreID,Date,IsHoliday,IsOpen,HasPromotions,StoreType,AssortmentType,NearestCompetitor,Region,NumberOfCustomers,...,Mean_TemperatureC,Mean_VisibilityKm,Mean_Wind_SpeedKm_h,Min_Dew_PointC,Min_Humidity,Min_Sea_Level_PressurehPa,Min_TemperatureC,Min_VisibilitykM,Precipitationmm,WindDirDegrees
0,1000,01/03/2016,0,1,0,Hyper Market,General,326,7,495,...,1,11.0,16,-2,70,1029,1,6.0,0.0,23
1,1000,02/03/2016,0,1,0,Hyper Market,General,326,7,608,...,3,13.0,10,-2,58,1025,1,10.0,0.0,56
2,1000,04/03/2016,0,1,0,Hyper Market,General,326,7,665,...,3,11.0,10,-3,55,1023,2,8.0,0.0,22
3,1000,05/03/2016,0,1,0,Hyper Market,General,326,7,630,...,3,15.0,10,-6,25,1022,-1,10.0,0.0,108
4,1000,06/03/2016,0,0,0,Hyper Market,General,326,7,0,...,1,12.0,5,-6,48,1022,-5,5.0,0.0,46

In [3]:
df['D_Day'] =  df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y').day)
df['D_DayOfYear'] =  df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y').timetuple().tm_yday)

In [4]:
df['D_Month'] =  df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y').month)

In [5]:
df['D_Year'] =  df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y').year)

In [6]:
df['D_DayOfweek'] =  df['Date'].apply(lambda x: datetime.strptime(x, '%d/%m/%Y').weekday())

In [7]:
df.head()

,StoreID,Date,IsHoliday,IsOpen,HasPromotions,StoreType,AssortmentType,NearestCompetitor,Region,NumberOfCustomers,...,Min_Sea_Level_PressurehPa,Min_TemperatureC,Min_VisibilitykM,Precipitationmm,WindDirDegrees,D_Day,D_DayOfYear,D_Month,D_Year,D_DayOfweek
0,1000,01/03/2016,0,1,0,Hyper Market,General,326,7,495,...,1029,1,6.0,0.0,23,1,61,3,2016,1
1,1000,02/03/2016,0,1,0,Hyper Market,General,326,7,608,...,1025,1,10.0,0.0,56,2,62,3,2016,2
2,1000,04/03/2016,0,1,0,Hyper Market,General,326,7,665,...,1023,2,8.0,0.0,22,4,64,3,2016,4
3,1000,05/03/2016,0,1,0,Hyper Market,General,326,7,630,...,1022,-1,10.0,0.0,108,5,65,3,2016,5
4,1000,06/03/2016,0,0,0,Hyper Market,General,326,7,0,...,1022,-5,5.0,0.0,46,6,66,3,2016,6

In [8]:
print("ATTRIBUTES LIST:")
pprint(list(df.columns))

print("\n\nSORTED ATTRIBUTES LIST:")
pprint(sorted(list(df.columns)))

ATTRIBUTES LIST:
['StoreID',
 'Date',
 'IsHoliday',
 'IsOpen',
 'HasPromotions',
 'StoreType',
 'AssortmentType',
 'NearestCompetitor',
 'Region',
 'NumberOfCustomers',
 'NumberOfSales',
 'Region_AreaKM2',
 'Region_GDP',
 'Region_PopulationK',
 'CloudCover',
 'Events',
 'Max_Dew_PointC',
 'Max_Gust_SpeedKm_h',
 'Max_Humidity',
 'Max_Sea_Level_PressurehPa',
 'Max_TemperatureC',
 'Max_VisibilityKm',
 'Max_Wind_SpeedKm_h',
 'Mean_Dew_PointC',
 'Mean_Humidity',
 'Mean_Sea_Level_PressurehPa',
 'Mean_TemperatureC',
 'Mean_VisibilityKm',
 'Mean_Wind_SpeedKm_h',
 'Min_Dew_PointC',
 'Min_Humidity',
 'Min_Sea_Level_PressurehPa',
 'Min_TemperatureC',
 'Min_VisibilitykM',
 'Precipitationmm',
 'WindDirDegrees',
 'D_Day',
 'D_DayOfYear',
 'D_Month',
 'D_Year',
 'D_DayOfweek']


SORTED ATTRIBUTES LIST:
['AssortmentType',
 'CloudCover',
 'D_Day',
 'D_DayOfYear',
 'D_DayOfweek',
 'D_Month',
 'D_Year',
 'Date',
 'Events',
 'HasPromotions',
 'IsHoliday',
 'IsOpen',
 'Max_Dew_PointC',
 'Max_Gust_SpeedKm_h',
 'Max_Humidity',
 'Max_Sea_Level_PressurehPa',
 'Max_TemperatureC',
 'Max_VisibilityKm',
 'Max_Wind_SpeedKm_h',
 'Mean_Dew_PointC',
 'Mean_Humidity',
 'Mean_Sea_Level_PressurehPa',
 'Mean_TemperatureC',
 'Mean_VisibilityKm',
 'Mean_Wind_SpeedKm_h',
 'Min_Dew_PointC',
 'Min_Humidity',
 'Min_Sea_Level_PressurehPa',
 'Min_TemperatureC',
 'Min_VisibilitykM',
 'NearestCompetitor',
 'NumberOfCustomers',
 'NumberOfSales',
 'Precipitationmm',
 'Region',
 'Region_AreaKM2',
 'Region_GDP',
 'Region_PopulationK',
 'StoreID',
 'StoreType',
 'WindDirDegrees']

### Write to file

In [9]:
# save the dataset
df.to_csv('./dataset/preprocessed0_date_train.csv', index=False)