In [1]:
from import_man import *

sns.set(style="white", color_codes=True)
sns.set_context(rc={"font.family":'sans',"font.size":24,"axes.titlesize":24,"axes.labelsize":24})  

import warnings 
warnings.filterwarnings("ignore")

%matplotlib inline

lags_list = ['t-14','t-7','t-1','t-2','t-9','t-8','t-6','t-15','t-21','t-13','t-20']

In [2]:
df = pd.read_csv("./dataset/enriched_train.csv")

In [3]:
df['StoreID'].astype('object').describe()

count     523000
unique       749
top         1748
freq         729
Name: StoreID, dtype: int64

In [4]:
# let's reduce the dataframe size
df.head().T

,0,1,2,3,4
StoreID,1000,1000,1000,1000,1000
Date,2016-03-23,2016-03-24,2016-03-25,2016-03-26,2016-03-27
IsHoliday,0,0,0,0,0
IsOpen,1,1,1,1,0
HasPromotions,1,1,1,0,0
StoreType,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market
AssortmentType,General,General,General,General,General
NearestCompetitor,326,326,326,326,326
Region,7,7,7,7,7
NumberOfCustomers,541,626,625,511,622.769
NumberOfSales,7109,8041,7890,6005,7675.45
Region_AreaKM2,9643,9643,9643,9643,9643
Region_GDP,17130,17130,17130,17130,17130
Region_PopulationK,2770,2770,2770,2770,2770
CloudCover,6,6,5,7,8
Events,Rain,Rain-Snow,None,None,None
Max_Dew_PointC,6,0,-1,-5,-10
Max_Humidity,100,87,93,64,48
Max_Sea_Level_PressurehPa,1012,1020,1020,1016,1016
Max_TemperatureC,9,5,7,3,6
Max_VisibilityKm,21,22,23,24,25
Max_Wind_SpeedKm_h,32,21,34,34,35
Mean_Dew_PointC,3,-2,-3,-7,-12
Mean_Humidity,89,71,61,52,34
Mean_Sea_Level_PressurehPa,1004,1017,1016,1015,1013
Mean_TemperatureC,5,3,3,1,2
Mean_VisibilityKm,21,22,23,24,25
Mean_Wind_SpeedKm_h,10,11,14,23,24
Min_Dew_PointC,-1,-4,-6,-10,-14
Min_Humidity,58,51,31,34,13
Min_Sea_Level_PressurehPa,1001,1012,1014,1014,1011
Min_TemperatureC,1,1,-1,-1,-2
Min_VisibilitykM,21,22,23,24,25
Precipitationmm,5.08,0,0,0,0
WindDirDegrees,191,331,59,67,59
D_Day,23,24,25,26,27
D_DayOfYear,83,84,85,86,87
D_Month,3,3,3,3,3
D_Year,2016,2016,2016,2016,2016
t-14,8804,7823,7989,5895,7675.45
t-7,6014,6087,6962,6618,7675.45
t-1,8155,7109,8041,7890,6005
t-2,9183,8155,7109,8041,7890
t-9,6348,4738,6014,6087,6962
t-8,4738,6014,6087,6962,6618
t-6,6087,6962,6618,7675.45,9183
t-15,9019,8804,7823,7989,5895
t-21,5676,8111,8300,7154,7675.45
t-13,7823,7989,5895,7675.45,6348
t-20,8111,8300,7154,7675.45,10110
MeanStoreSales,7682.75,7682.75,7682.75,7682.75,7682.75
MeanRegionSales,4698.57,4698.57,4698.57,4698.57,4698.57
D_Day_of_week,2,3,4,5,6

In [5]:
df.describe()

,StoreID,IsHoliday,IsOpen,HasPromotions,NearestCompetitor,Region,NumberOfCustomers,NumberOfSales,Region_AreaKM2,Region_GDP,...,t-9,t-8,t-6,t-15,t-21,t-13,t-20,MeanStoreSales,MeanRegionSales,D_Day_of_week
count,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,...,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000,523000.000000
mean,1373.968929,0.029719,0.829713,0.383294,8003.019463,5.713099,311.210993,4882.344267,12381.375667,14050.424199,...,4882.394625,4882.392218,4882.388795,4882.442570,4882.487767,4882.422067,4882.486345,4882.344267,4882.344267,2.996424
std,216.387189,0.169811,0.375885,0.486190,11537.836616,3.357248,152.731463,2130.490604,9140.859470,2755.411625,...,2130.506240,2130.505295,2130.504875,2130.527667,2130.550938,2130.514731,2130.550657,1707.694458,444.514184,2.000534
min,1000.000000,0.000000,0.000000,0.000000,47.000000,0.000000,0.000000,0.000000,344.000000,9893.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1912.614876,4091.116766,0.000000
25%,1187.000000,0.000000,1.000000,0.000000,1057.000000,3.000000,215.106136,3448.000000,7215.000000,11849.000000,...,3448.000000,3448.000000,3448.000000,3448.000000,3448.000000,3448.000000,3448.000000,3709.673300,4679.834832,1.000000
50%,1373.000000,0.000000,1.000000,0.000000,3321.000000,6.000000,278.000000,4494.000000,9643.000000,15017.000000,...,4494.000000,4494.000000,4494.000000,4494.000000,4494.000000,4494.000000,4494.000000,4650.500829,4783.031470,3.000000
75%,1561.000000,0.000000,1.000000,1.000000,9673.000000,9.000000,366.000000,5860.604613,15566.000000,15931.000000,...,5860.604613,5860.604613,5860.604613,5860.604613,5860.604613,5860.604613,5860.604613,5676.378109,4945.394548,5.000000
max,1748.000000,1.000000,1.000000,1.000000,85070.000000,10.000000,2206.000000,26641.000000,32221.000000,23931.000000,...,26641.000000,26641.000000,26641.000000,26641.000000,26641.000000,26641.000000,26641.000000,15312.660626,5828.772892,6.000000

In [6]:
import modify_dataset as md
train = md.get_fake_train(df)
test = md.get_fake_test(df)

df_train_test = df
df_train_test.ix[((df['D_Month'] == 1) | (df['D_Month'] == 2)) & (df['D_Year'] == 2018), lags_list + ['NumberOfSales']] = 0

#pprint(list(df_train_test.columns))
#df_train_test.head()
df_train_test[700:740].T

,700,701,702,703,704,705,706,707,708,709,...,730,731,732,733,734,735,736,737,738,739
StoreID,1000,1000,1000,1000,1000,1000,1000,1000,1001,1001,...,1001,1001,1001,1001,1001,1001,1001,1001,1001,1001
Date,2018-02-21,2018-02-22,2018-02-23,2018-02-24,2018-02-25,2018-02-26,2018-02-27,2018-02-28,2016-03-01,2016-03-02,...,2016-03-24,2016-03-25,2016-03-26,2016-03-27,2016-03-28,2016-03-29,2016-03-30,2016-03-31,2016-04-01,2016-04-02
IsHoliday,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
IsOpen,1,1,1,1,0,1,1,1,1,1,...,1,1,1,0,1,1,1,1,0,1
HasPromotions,1,1,1,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,1,1,0
StoreType,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Super Market,Super Market,...,Super Market,Super Market,Super Market,Super Market,Super Market,Super Market,Super Market,Super Market,Super Market,Super Market
AssortmentType,General,General,General,General,General,General,General,General,With Non-Food Department,With Non-Food Department,...,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department,With Non-Food Department
NearestCompetitor,326,326,326,326,326,326,326,326,16755,16755,...,16755,16755,16755,16755,16755,16755,16755,16755,16755,16755
Region,7,7,7,7,7,7,7,7,0,0,...,0,0,0,0,0,0,0,0,0,0
NumberOfCustomers,561,537,558,497,622.769,415,493,504,118,128,...,116,148,145,194.358,133,148,161,193,194.358,198
NumberOfSales,0,0,0,0,0,0,0,0,1366,1597,...,1442,1770,1674,3154.47,1583,1814,2045,2468,3154.47,2369
Region_AreaKM2,9643,9643,9643,9643,9643,9643,9643,9643,8410,8410,...,8410,8410,8410,8410,8410,8410,8410,8410,8410,8410
Region_GDP,17130,17130,17130,17130,17130,17130,17130,17130,10494,10494,...,10494,10494,10494,10494,10494,10494,10494,10494,10494,10494
Region_PopulationK,2770,2770,2770,2770,2770,2770,2770,2770,1892,1892,...,1892,1892,1892,1892,1892,1892,1892,1892,1892,1892
CloudCover,7,8,6,7,5,7,5,4,7,7,...,6,6,5,0,8,8,8,7,7,7
Events,None,None,None,Rain,Rain,Rain-Snow,Fog-Rain,Fog-Rain,Fog-Rain,Fog-Rain,...,Fog-Rain-Snow,Snow,Snow,None,None,None,Snow,Snow,Snow,Snow
Max_Dew_PointC,1,-1,2,4,1,4,2,2,1,2,...,1,-2,-7,-10,-10,-9,-5,-2,0,-2
Max_Humidity,93,87,87,93,100,100,100,100,100,100,...,100,100,86,74,74,80,80,93,100,100
Max_Sea_Level_PressurehPa,1042,1038,1026,1005,1012,1009,1016,1022,1033,1031,...,1020,1023,1026,1026,1022,1017,1015,1014,1009,1010
Max_TemperatureC,6,2,11,7,7,4,7,8,1,2,...,3,-2,-4,-2,-1,1,1,1,1,3
Max_VisibilityKm,721,722,723,724,725,726,727,728,729,730,...,751,752,753,754,755,756,757,758,759,760
Max_Wind_SpeedKm_h,14,19,26,26,16,21,29,19,13,14,...,21,23,34,40,45,37,35,21,29,13
Mean_Dew_PointC,0,-2,0,1,-1,1,2,1,0,1,...,-2,-4,-13,-14,-11,-11,-9,-4,-2,-4
Mean_Humidity,77,77,66,71,79,94,82,82,98,94,...,90,87,59,52,58,53,58,79,87,77
Mean_Sea_Level_PressurehPa,1040,1031,1015,1000,1009,1001,1008,1019,1030,1026,...,1014,1020,1023,1022,1017,1014,1013,1011,1005,1006
Mean_TemperatureC,3,1,6,4,3,2,3,3,0,1,...,0,-3,-7,-7,-4,-3,-2,-1,-1,0
Mean_VisibilityKm,721,722,723,724,725,726,727,728,729,730,...,751,752,753,754,755,756,757,758,759,760
Mean_Wind_SpeedKm_h,5,11,13,16,6,14,14,8,8,5,...,11,13,23,23,29,19,19,13,14,6
Min_Dew_PointC,-1,-3,-2,-2,-2,0,0,-1,-1,-2,...,-4,-7,-17,-17,-12,-14,-12,-6,-3,-6
Min_Humidity,53,65,40,39,44,81,58,49,92,76,...,73,61,26,27,32,19,24,60,62,46
Min_Sea_Level_PressurehPa,1037,1025,1003,997,1004,998,1001,1015,1029,1022,...,1007,1017,1020,1019,1014,1012,1012,1007,1003,1005
Min_TemperatureC,2,0,1,1,-1,0,1,-2,-1,0,...,-2,-5,-10,-12,-7,-8,-5,-3,-3,-3
Min_VisibilitykM,721,722,723,724,725,726,727,728,729,730,...,751,752,753,754,755,756,757,758,759,760
Precipitationmm,0,0,0,2.03,0,7.11,0,0,0,0,...,0.51,0,0,0,0,0,0,0,0,0
WindDirDegrees,111,193,194,214,211,187,198,210,29,311,...,306,355,75,84,77,62,77,108,223,319
D_Day,21,22,23,24,25,26,27,28,1,2,...,24,25,26,27,28,29,30,31,1,2
D_DayOfYear,52,53,54,55,56,57,58,59,61,62,...,84,85,86,87,88,89,90,91,92,93
D_Month,2,2,2,2,2,2,2,2,3,3,...,3,3,3,3,3,3,3,3,4,4
D_Year,2018,2018,2018,2018,2018,2018,2018,2018,2016,2016,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
t-14,0,0,0,0,0,0,0,0,5214,6133,...,1361,1669,1686,3154.47,1279,950,899,1324,1732,1825
t-7,0,0,0,0,0,0,0,0,6870,6778,...,1324,1732,1825,3154.47,1401,1007,1362,1442,1770,1674
t-1,0,0,0,0,0,0,0,0,5591,1366,...,1362,1442,1770,1674,3154.47,1583,1814,2045,2468,3154.47
t-2,0,0,0,0,0,0,0,0,5368,5591,...,1007,1362,1442,1770,1674,3154.47,1583,1814,2045,2468
t-9,0,0,0,0,0,0,0,0,7891,6775,...,950,899,1324,1732,1825,3154.47,1401,1007,1362,1442
t-8,0,0,0,0,0,0,0,0,6775,6870,...,899,1324,1732,1825,3154.47,1401,1007,1362,1442,1770
t-6,0,0,0,0,0,0,0,0,6778,5450,...,1732,1825,3154.47,1401,1007,1362,1442,1770,1674,3154.47
t-15,0,0,0,0,0,0,0,0,5437,5214,...,1256,1361,1669,1686,3154.47,1279,950,899,1324,1732
t-21,0,0,0,0,0,0,0,0,7142,7763,...,1597,1805,1660,3154.47,1380,1290,1256,1361,1669,1686
t-13,0,0,0,0,0,0,0,0,6133,6939,...,1669,1686,3154.47,1279,950,899,1324,1732,1825,3154.47
t-20,0,0,0,0,0,0,0,0,7763,6374,...,1805,1660,3154.47,1380,1290,1256,1361,1669,1686,3154.47
MeanStoreSales,7682.75,7682.75,7682.75,7682.75,7682.75,7682.75,7682.75,7682.75,3154.47,3154.47,...,3154.47,3154.47,3154.47,3154.47,3154.47,3154.47,3154.47,3154.47,3154.47,3154.47
MeanRegionSales,4698.57,4698.57,4698.57,4698.57,4698.57,4698.57,4698.57,4698.57,4881.92,4881.92,...,4881.92,4881.92,4881.92,4881.92,4881.92,4881.92,4881.92,4881.92,4881.92,4881.92
D_Day_of_week,2,3,4,5,6,0,1,2,1,2,...,3,4,5,6,0,1,2,3,4,5

In [7]:
test['StoreID'].astype('object').describe()

count     43816
unique      749
top        1748
freq         59
Name: StoreID, dtype: int64

In [8]:

#features = ['Max_Dew_PointC','Max_Humidity','Max_Sea_Level_PressurehPa','Max_TemperatureC',
#           'Max_Wind_SpeedKm_h','Mean_Dew_PointC','Mean_Humidity','Mean_Sea_Level_PressurehPa',
#            'Mean_TemperatureC','Mean_Wind_SpeedKm_h','Min_Dew_PointC','Min_Humidity',
#           'Min_Sea_Level_PressurehPa','Min_TemperatureC','Precipitationmm','Mean_VisibilityKm']
# Separating out the features

features = lags_list + ['MeanStoreSales']

x = train[features]
# Separating out the target
y = train['NumberOfSales']
x.head()

,t-14,t-7,t-1,t-2,t-9,t-8,t-6,t-15,t-21,t-13,t-20,MeanStoreSales
0,8804.000000,6014.000000,8155.0,9183.0,6348.0,4738.0,6087.000000,9019.0,5676.000000,7823.000000,8111.000000,7682.751625
1,7823.000000,6087.000000,7109.0,8155.0,4738.0,6014.0,6962.000000,8804.0,8111.000000,7989.000000,8300.000000,7682.751625
2,7989.000000,6962.000000,8041.0,7109.0,6014.0,6087.0,6618.000000,7823.0,8300.000000,5895.000000,7154.000000,7682.751625
3,5895.000000,6618.000000,7890.0,8041.0,6087.0,6962.0,7675.446488,7989.0,7154.000000,7675.446488,7675.446488,7682.751625
4,7675.446488,7675.446488,6005.0,7890.0,6962.0,6618.0,9183.000000,5895.0,7675.446488,6348.000000,10110.000000,7682.751625

In [9]:
test.head()

,StoreID,Date,IsHoliday,IsOpen,HasPromotions,StoreType,AssortmentType,NearestCompetitor,Region,NumberOfCustomers,...,t-9,t-8,t-6,t-15,t-21,t-13,t-20,MeanStoreSales,MeanRegionSales,D_Day_of_week
649,1000,2018-01-01,0,1,0,Hyper Market,General,326,7,642.000000,...,9835.000000,7675.446488,10650.000000,7675.446488,7368.0,10520.0,6858.0,7682.751625,4698.572717,0
650,1000,2018-01-02,0,1,0,Hyper Market,General,326,7,746.000000,...,7675.446488,11881.000000,4498.000000,12353.000000,6858.0,9479.0,5890.0,7682.751625,4698.572717,1
651,1000,2018-01-03,0,1,0,Hyper Market,General,326,7,333.000000,...,11881.000000,10650.000000,7675.446488,10520.000000,5890.0,10529.0,6913.0,7682.751625,4698.572717,2
652,1000,2018-01-04,1,0,0,Hyper Market,General,326,7,622.769231,...,10650.000000,4498.000000,7675.446488,9479.000000,6913.0,9050.0,7282.0,7682.751625,4698.572717,3
653,1000,2018-01-05,0,1,0,Hyper Market,General,326,7,536.000000,...,4498.000000,7675.446488,8930.000000,10529.000000,7282.0,9835.0,9179.0,7682.751625,4698.572717,4

days = test['Date'].loc[:'Date'].values
days

In [10]:
import sklearn.linear_model
model = sklearn.linear_model.LinearRegression(fit_intercept=True, normalize=True, copy_X=False, n_jobs=-1).fit(x, y)
model.coef_

array([ 0.46990029,  0.10011236,  0.40130522,  0.1202943 , -0.0995176 ,
       -0.11358087, -0.04022331, -0.2442403 ,  0.11728318,  0.05857282,
       -0.05393229,  0.2933977 ])

row = test.loc[(test['Date'].values == '2018-01-01')]
pred = model.predict(row[features])
pred = pd.DataFrame(pred,columns=['NumberOfSales'],index=row['StoreID'].values)
pred['Date']=row['Date'].values
pred

df_dbd = pd.DataFrame(columns=['NumberOfSales','Date'])
df_dbd = pd.concat((df_dbd,pred))
df_dbd

In [11]:
days = test['Date'].loc[:'Date'].values
len(days)

43816

In [12]:
days=list(set(days))

In [13]:
len(days)

59

In [14]:
days=sorted(days)
days

['2018-01-01',
 '2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-06',
 '2018-01-07',
 '2018-01-08',
 '2018-01-09',
 '2018-01-10',
 '2018-01-11',
 '2018-01-12',
 '2018-01-13',
 '2018-01-14',
 '2018-01-15',
 '2018-01-16',
 '2018-01-17',
 '2018-01-18',
 '2018-01-19',
 '2018-01-20',
 '2018-01-21',
 '2018-01-22',
 '2018-01-23',
 '2018-01-24',
 '2018-01-25',
 '2018-01-26',
 '2018-01-27',
 '2018-01-28',
 '2018-01-29',
 '2018-01-30',
 '2018-01-31',
 '2018-02-01',
 '2018-02-02',
 '2018-02-03',
 '2018-02-04',
 '2018-02-05',
 '2018-02-06',
 '2018-02-07',
 '2018-02-08',
 '2018-02-09',
 '2018-02-10',
 '2018-02-11',
 '2018-02-12',
 '2018-02-13',
 '2018-02-14',
 '2018-02-15',
 '2018-02-16',
 '2018-02-17',
 '2018-02-18',
 '2018-02-19',
 '2018-02-20',
 '2018-02-21',
 '2018-02-22',
 '2018-02-23',
 '2018-02-24',
 '2018-02-25',
 '2018-02-26',
 '2018-02-27',
 '2018-02-28']

In [15]:
df_dbd = pd.DataFrame(columns=['NumberOfSales','Date'])
df_dbd

Empty DataFrame
Columns: [NumberOfSales, Date]
Index: []

In [16]:
print("Train n rows {}, Test n rows {}".format(train.shape[0], test.shape[0]))

Train n rows 479184, Test n rows 43816

In [26]:

df_train_test_TMP = df_train_test

# for d in days[:1]:
d = '2018-01-01'

stores_rows = df_train_test_TMP.loc[(df_train_test_TMP['Date'].values == d)]

    # stores_pred = model.predict(stores_rows[features])
    # stores_pred = pd.DataFrame(stores_pred, columns=['NumberOfSales'], index=stores_rows['StoreID'].values)
    # stores_pred['Date'] = stores_rows['Date'].values
    # df_dbd = pd.concat((df_dbd, stores_pred))
print(stores_rows.shape)
stores_rows.head()


lags_ordered = [7, 14, 1, 2, 9, 8, 6, 15, 21, 13, 20]
lags_name = ['t-' + str(i) for i in lags_ordered]

for i in range(len(lags_ordered)):
    stores_rows[lags_name[i]] = df_train_test_TMP['NumberOfSales'].shift(lags_ordered[i])

stores_pred = model.predict(stores_rows[features])
print(stores_pred[:5])
df_stores_pred = pd.DataFrame(stores_pred, columns=['NumberOfSales'], index=stores_rows.index)

#df = pd.DataFrame({'A': ['a', 'b', 'c'],
#                  'B': ['x', 'y', 'z']})
#print(stores_rows.index)
#print(type(stores_rows.index))
#print(type(list(stores_rows.index)))
#df_stores_pred

new_column = pd.Series(stores_pred, name='NumberOfSales', index=stores_rows.index)
df_train_test_TMP.update(new_column)

#print(new_column)
#df_train_test[df_train_test['Date'].values == d].apply(lambda x) = df_stores_pred['NumberOfSales']


#df_train_test.loc[(df_train_test['Date'].values == d)]

n = 2100
df_train_test_TMP[n:n+50].T

(624, 53)
[10326.68102333  5368.31555795  6383.25900037  7838.08556585
  6954.06635428]

,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,...,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149
StoreID,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002,...,1002,1002,1002,1002,1002,1002,1002,1002,1002,1002
Date,2017-12-25,2017-12-26,2017-12-27,2017-12-28,2017-12-29,2017-12-30,2017-12-31,2018-01-01,2018-01-02,2018-01-03,...,2018-02-03,2018-02-04,2018-02-05,2018-02-06,2018-02-07,2018-02-08,2018-02-09,2018-02-10,2018-02-11,2018-02-12
IsHoliday,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
IsOpen,1,1,1,0,0,1,0,1,1,1,...,1,0,1,1,1,1,1,1,0,1
HasPromotions,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,0,0,0
StoreType,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,...,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market,Hyper Market
AssortmentType,General,General,General,General,General,General,General,General,General,General,...,General,General,General,General,General,General,General,General,General,General
NearestCompetitor,370,370,370,370,370,370,370,370,370,370,...,370,370,370,370,370,370,370,370,370,370
Region,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
NumberOfCustomers,412,438,211,379.586,379.586,361,379.586,420,422,198,...,352,379.586,465,397,373,393,368,299,379.586,381
NumberOfSales,5708,6149,3092,4968.05,4968.05,5110,4968.05,6383.26,0,0,...,0,0,0,0,0,0,0,0,0,0
Region_AreaKM2,407,407,407,407,407,407,407,407,407,407,...,407,407,407,407,407,407,407,407,407,407
Region_GDP,13155,13155,13155,13155,13155,13155,13155,13155,13155,13155,...,13155,13155,13155,13155,13155,13155,13155,13155,13155,13155
Region_PopulationK,1584,1584,1584,1584,1584,1584,1584,1584,1584,1584,...,1584,1584,1584,1584,1584,1584,1584,1584,1584,1584
CloudCover,7,7,6,5,5,5,5,6,7,7,...,6,6,5,6,6,5,5,6,4,7
Events,Rain,Rain,Rain,Rain,Fog-Snow,Fog,Snow,Fog-Snow,Rain-Snow,Fog-Rain,...,Snow,Snow,Rain-Snow,Snow,Snow,None,Fog-Rain-Snow,Fog-Rain,Rain-Snow,Rain-Snow
Max_Dew_PointC,9,10,8,3,0,-4,-3,-3,1,4,...,1,1,1,1,-2,-2,-3,2,1,4
Max_Humidity,95,97,93,93,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,75,100
Max_Sea_Level_PressurehPa,1015,1012,1013,1021,1027,1024,1027,1034,1034,1032,...,984,992,997,1006,1018,1030,1032,1032,1024,1023
Max_TemperatureC,12,11,9,7,1,-2,-3,-2,1,4,...,1,3,2,1,-1,2,-3,4,3,6
Max_VisibilityKm,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,...,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170
Max_Wind_SpeedKm_h,50,50,40,43,14,24,23,14,14,19,...,23,24,29,19,14,19,16,29,29,23
Mean_Dew_PointC,8,8,6,1,-2,-5,-7,-4,-2,2,...,-1,-1,-1,-1,-2,-4,-5,-2,-6,3
Mean_Humidity,87,84,84,79,93,91,89,96,96,100,...,95,88,89,94,90,81,92,96,54,90
Mean_Sea_Level_PressurehPa,1009,1010,1010,1014,1025,1014,1022,1028,1030,1030,...,979,988,994,1000,1011,1024,1031,1024,1019,1019
Mean_TemperatureC,9,10,7,4,-2,-4,-6,-4,-3,2,...,0,2,0,-1,-1,-1,-4,-2,1,2
Mean_VisibilityKm,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,...,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170
Mean_Wind_SpeedKm_h,35,34,27,23,6,10,11,8,8,11,...,14,18,18,11,8,6,10,13,21,16
Min_Dew_PointC,5,7,3,-1,-5,-7,-9,-7,-5,1,...,-2,-2,-2,-3,-3,-6,-7,-9,-12,-4
Min_Humidity,75,68,70,53,75,81,75,86,86,97,...,87,74,73,81,82,47,83,75,21,65
Min_Sea_Level_PressurehPa,1007,1009,1008,1013,1022,1010,1014,1022,1029,1029,...,974,984,992,996,1005,1018,1029,1013,1013,1017
Min_TemperatureC,6,9,4,2,-5,-6,-8,-7,-8,-1,...,-1,0,-2,-2,-2,-3,-7,-8,-1,-1
Min_VisibilitykM,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,...,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170
Precipitationmm,0,1.02,3.05,0,1.02,0,0,0,0.51,0.76,...,0,0,0,0.25,0,0,0,0,0,0
WindDirDegrees,250,255,251,270,288,91,305,293,218,258,...,261,243,250,275,288,49,44,265,318,284
D_Day,25,26,27,28,29,30,31,1,2,3,...,3,4,5,6,7,8,9,10,11,12
D_DayOfYear,359,360,361,362,363,364,365,1,2,3,...,34,35,36,37,38,39,40,41,42,43
D_Month,12,12,12,12,12,12,12,1,1,1,...,2,2,2,2,2,2,2,2,2,2
D_Year,2017,2017,2017,2017,2017,2017,2017,2018,2018,2018,...,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018
t-14,5029,4786,4142,4080,3925,5000,4968.05,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-7,7483,7037,5878,6415,5868,4587,4968.05,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-1,4968.05,5708,6149,3092,4968.05,4968.05,5110,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-2,4587,4968.05,5708,6149,3092,4968.05,4968.05,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-9,5000,4968.05,7483,7037,5878,6415,5868,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-8,4968.05,7483,7037,5878,6415,5868,4587,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-6,7037,5878,6415,5868,4587,4968.05,5708,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-15,4968.05,5029,4786,4142,4080,3925,5000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-21,6732,5488,6332,5339,6374,4620,4968.05,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-13,4786,4142,4080,3925,5000,4968.05,7483,0,0,0,...,0,0,0,0,0,0,0,0,0,0
t-20,5488,6332,5339,6374,4620,4968.05,5029,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MeanStoreSales,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,...,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05,4968.05
MeanRegionSales,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,...,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77,5828.77
D_Day_of_week,0,1,2,3,4,5,6,0,1,2,...,5,6,0,1,2,3,4,5,6,0

In [ ]:
from datetime import datetime
tmp = df_train_test[pd.to_datetime(df_train_test.Date) > datetime(2017, 11, 30)]
tmp = tmp[tmp.StoreID == 1001]
tmp[['StoreID', 'Date', 'NumberOfSales']].head(35)

In [ ]:
rows = test.loc[(test['Date'].values == d)]
pred = model.predict(rows[features])
pred = pd.DataFrame(pred,columns=['NumberOfSales'],index=rows['StoreID'].values)
pred['Date']=rows['Date'].values
df_dbd = pd.concat((df_dbd,pred))

for store in Stores
    test.loc[(test['Date'].values == d) & test['StoreID'] == store)].['NumberOfSales']

In [ ]:
test.loc[(test['Date'].values == '2018-02-28' ) & (test['StoreID'] == 1748 )].['NumberOfSales']