# One Hot Encoding 
One Hot Encoding is needed on the categorical variables to use them for regression or any other kind of computation.
Special attention must be paid to Events, since it has many possible values separated by a dash

In [2]:
import pandas as pd
import numpy as np

In [22]:
dataset = pd.read_csv('./dataset/train.csv')

In [4]:
print("Different values of StoreType")
print(dataset.StoreType.unique())

print("\nDifferent values of AssortmentType")
print(dataset.AssortmentType.unique())

print("\nDifferent values of Events")
print(dataset.Events.unique())

Different values of StoreType
['Hyper Market' 'Super Market' 'Standard Market' 'Shopping Center']

Different values of AssortmentType
['General' 'With Non-Food Department' 'With Fish Department']

Different values of Events
['Rain-Snow' 'Snow' 'Rain' nan 'Fog-Rain' 'Fog-Rain-Snow' 'Fog'
 'Rain-Thunderstorm' 'Rain-Hail' 'Fog-Rain-Thunderstorm'
 'Fog-Rain-Hail-Thunderstorm' 'Rain-Snow-Hail' 'Fog-Rain-Snow-Hail'
 'Fog-Snow' 'Snow-Hail' 'Fog-Thunderstorm' 'Thunderstorm' 'Fog-Snow-Hail'
 'Rain-Snow-Hail-Thunderstorm' 'Fog-Rain-Hail' 'Rain-Hail-Thunderstorm'
 'Rain-Snow-Thunderstorm']

In [26]:
dataset.describe()

,StoreID,IsHoliday,IsOpen,HasPromotions,NearestCompetitor,Region,NumberOfCustomers,NumberOfSales,Region_AreaKM2,Region_GDP,...,Mean_TemperatureC,Mean_VisibilityKm,Mean_Wind_SpeedKm_h,Min_Dew_PointC,Min_Humidity,Min_Sea_Level_PressurehPa,Min_TemperatureC,Min_VisibilitykM,Precipitationmm,WindDirDegrees
count,523021.000000,523021.000000,523021.000000,523021.000000,523021.00000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,...,523021.000000,511683.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,511683.000000,523021.000000,523021.000000
mean,1373.953914,0.029718,0.829714,0.383292,8002.71122,5.713151,259.325073,4057.377536,12381.265718,14050.547848,...,10.273205,12.151025,11.724961,3.737584,51.375624,1012.078435,6.202315,7.223408,0.808278,170.458096
std,216.395820,0.169808,0.375884,0.486189,11537.70753,3.357190,185.857102,2729.630381,9140.692427,2755.425404,...,7.041167,4.978385,5.791031,5.909098,19.284023,8.699236,6.312993,4.899575,2.631428,101.728193
min,1000.000000,0.000000,0.000000,0.000000,47.00000,0.000000,0.000000,0.000000,344.000000,9893.000000,...,-13.000000,0.000000,2.000000,-18.000000,10.000000,970.000000,-15.000000,0.000000,0.000000,-1.000000
25%,1187.000000,0.000000,1.000000,0.000000,1057.00000,3.000000,166.000000,2573.000000,7215.000000,11849.000000,...,4.000000,10.000000,8.000000,-1.000000,36.000000,1007.000000,1.000000,3.000000,0.000000,75.000000
50%,1373.000000,0.000000,1.000000,0.000000,3321.00000,6.000000,251.000000,4020.000000,9643.000000,15017.000000,...,11.000000,11.000000,11.000000,4.000000,51.000000,1013.000000,7.000000,8.000000,0.000000,191.000000
75%,1561.000000,0.000000,1.000000,1.000000,9673.00000,9.000000,345.000000,5538.000000,15566.000000,15931.000000,...,16.000000,14.000000,14.000000,8.000000,66.000000,1018.000000,11.000000,10.000000,0.250000,250.000000
max,1748.000000,1.000000,1.000000,1.000000,85070.00000,10.000000,2206.000000,26641.000000,32221.000000,23931.000000,...,30.000000,31.000000,53.000000,18.000000,100.000000,1038.000000,24.000000,31.000000,58.930000,360.000000

## OHE for StoreType

In [27]:
def OHE_StoreType_SuperMarket(value):
    return 1 if value=='Super Market' else 0

def OHE_StoreType_HyperMarket(value):
    return 1 if value=='Hyper Market' else 0

def OHE_StoreType_StandardMarket(value):
    return 1 if value=='Standard Market' else 0

def OHE_StoreType_ShoppingCenter(value):
    return 1 if value=='Shopping Center' else 0

In [28]:
dataset['StoreType_SuperMarket'] = dataset.StoreType.apply(OHE_StoreType_SuperMarket)
dataset['StoreType_HyperMarket'] = dataset.StoreType.apply(OHE_StoreType_HyperMarket)
dataset['StoreType_StandardMarket'] = dataset.StoreType.apply(OHE_StoreType_StandardMarket)
dataset['StoreType_ShoppingCenter'] = dataset.StoreType.apply(OHE_StoreType_ShoppingCenter)

## OHE for AssortmentType

In [30]:
def OHE_AssortmentType_General(value):
    return 1 if value=='General' else 0

def OHE_AssortmentType_WithNFDepartment(value):
    return 1 if value=='With Non-Food Department' else 0

def OHE_AssortmentType_WithFishDepartment(value):
    return 1 if value=='With Fish Department' else 0

In [31]:
dataset['AssortmentType_General'] = dataset.AssortmentType.apply(OHE_AssortmentType_General)
dataset['AssortmentType_WithNFDept'] = dataset.AssortmentType.apply(OHE_AssortmentType_WithNFDepartment)
dataset['AssortmentType_WithFishDept'] = dataset.AssortmentType.apply(OHE_AssortmentType_WithFishDepartment)

In [32]:
dataset.describe()

,StoreID,IsHoliday,IsOpen,HasPromotions,NearestCompetitor,Region,NumberOfCustomers,NumberOfSales,Region_AreaKM2,Region_GDP,...,Min_VisibilitykM,Precipitationmm,WindDirDegrees,StoreType_SuperMarket,StoreType_HyperMarket,StoreType_StandardMarket,StoreType_ShoppingCenter,AssortmentType_General,AssortmentType_WithNFDept,AssortmentType_WithFishDept
count,523021.000000,523021.000000,523021.000000,523021.000000,523021.00000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,...,511683.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000,523021.000000
mean,1373.953914,0.029718,0.829714,0.383292,8002.71122,5.713151,259.325073,4057.377536,12381.265718,14050.547848,...,7.223408,0.808278,170.458096,0.142834,0.559765,0.284857,0.012544,0.566302,0.429516,0.004181
std,216.395820,0.169808,0.375884,0.486189,11537.70753,3.357190,185.857102,2729.630381,9140.692427,2755.425404,...,4.899575,2.631428,101.728193,0.349903,0.496416,0.451347,0.111297,0.495585,0.495008,0.064529
min,1000.000000,0.000000,0.000000,0.000000,47.00000,0.000000,0.000000,0.000000,344.000000,9893.000000,...,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1187.000000,0.000000,1.000000,0.000000,1057.00000,3.000000,166.000000,2573.000000,7215.000000,11849.000000,...,3.000000,0.000000,75.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1373.000000,0.000000,1.000000,0.000000,3321.00000,6.000000,251.000000,4020.000000,9643.000000,15017.000000,...,8.000000,0.000000,191.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,1561.000000,0.000000,1.000000,1.000000,9673.00000,9.000000,345.000000,5538.000000,15566.000000,15931.000000,...,10.000000,0.250000,250.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
max,1748.000000,1.000000,1.000000,1.000000,85070.00000,10.000000,2206.000000,26641.000000,32221.000000,23931.000000,...,31.000000,58.930000,360.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Notice that for instance AssortmentType_WithFishDept has only a few cases (since the mean is 0.004) and it refers to all examples, since every store has more than 700 tuples (one per each observation day), it means that only a few stores (e.g. 2 or 3 stores) have a AssortmentType_WithFishDept, we could discard cases like that or we could treat those stores separately